version: '3.8'

services:
  api:
    build: .
    container_name: api-imersao-alura
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Garante que os logs do python apareçam imediatamente
